type AreaCodes = Record<string, { name: string; query?: string } | undefined>

const UNUSED_GEOGRAPHIC = { name: 'Unused - Available for Geographic Use', query: 'Land' }
const UNUSED_NON_GEOGRAPHIC = { name: 'Unused - Available for Non-Geographic Use', query: 'City wallpaper' }
const N11 = { name: 'Reserved for Regional Services', query: 'Emergency Services' }
const COMING_SOON = { name: 'Coming Soon!', query: 'Coming soon wallpaper' }
const PERSONAL_COMMUNICATIONS = { name: 'For Personal Communications', query: 'Person talking on phone' }
const CANADIAN_NON_GEOGRAPHIC = { name: 'Canadian Non-Geographic', query: 'Canada' }
const US_GOV_SPECIAL_SERVICES = { name: 'US Government Special Use', query: 'US Government' }
const TOLL_FREE = { name: 'Toll-Free Service', query: 'Pay Phone' }
const NOT_ASSIGNABLE = { name: 'Not Usable as Area Code', query: 'Impossible' }
const DIRECTORY_ASSISTANCE = { name: 'Reserved for Directory Assistance', query: 'Phone call background' }
const CARRIER_INTERNAL_USE = { name: 'Reserved for Carrier Use', query: 'Phone call background' }
const PREMIUM_RATE = { name: 'Premium-Rate Numbers', query: 'Phone call background' }

export const AREA_CODES_MAP: AreaCodes = {
  '200': UNUSED_NON_GEOGRAPHIC,
  '201': { name: 'New Jersey (Jersey City)' },
  '202': { name: 'Washington, D.C.' },
  '203': { name: 'Connecticut (New Haven, Stamford)' },
  '204': { name: 'Manitoba, Canada' },
  '205': { name: 'Alabama (Birmingham, Tuscaloosa)' },
  '206': { name: 'Washington (Seattle)' },
  '207': { name: 'Maine' },
  '208': { name: 'Idaho' },
  '209': { name: 'California (Stockton, Modesto)' },
  '210': { name: 'Texas (San Antonio)' },
  '211': N11,
  '212': { name: 'New York City (Manhattan)' },
  '213': { name: 'California (Los Angeles)' },
  '214': { name: 'Texas (Dallas)' },
  '215': { name: 'Pennsylvania (Philadelphia)' },
  '216': { name: 'Ohio (Cleveland)' },
  '217': { name: 'Illinois (Springfield, Champaign)' },
  '218': { name: 'Minnesota (Duluth)' },
  '219': { name: 'Indiana (Gary, Hammond)' },
  '220': { name: 'Ohio' },
  '221': UNUSED_GEOGRAPHIC,
  '222': UNUSED_NON_GEOGRAPHIC,
  '223': { name: 'Pennsylvania' },
  '224': { name: 'Illinois' },
  '225': { name: 'Louisiana (Baton Rouge)' },
  '226': { name: 'Ontario, Canada' },
  '227': { name: 'Maryland' },
  '228': { name: 'Mississippi (Gulfport, Biloxi)' },
  '229': { name: 'Georgia (Albany, Valdosta)' },
  '230': UNUSED_GEOGRAPHIC,
  '231': { name: 'Michigan (Traverse City, Muskegon)' },
  '232': UNUSED_GEOGRAPHIC,
  '233': UNUSED_NON_GEOGRAPHIC,
  '234': { name: 'Ohio' },
  '235': { name: 'Missouri' },
  '236': { name: 'British Columbia, Canada' },
  '237': UNUSED_GEOGRAPHIC,
  '238': UNUSED_GEOGRAPHIC,
  '239': { name: 'Florida (Fort Myers, Naples)' },
  '240': { name: 'Maryland' },
  '241': UNUSED_GEOGRAPHIC,
  '242': { name: 'Bahamas' },
  '243': UNUSED_GEOGRAPHIC,
  '244': UNUSED_NON_GEOGRAPHIC,
  '245': UNUSED_GEOGRAPHIC,
  '246': { name: 'Barbados' },
  '247': UNUSED_GEOGRAPHIC,
  '248': { name: 'Michigan (Pontiac, Troy)' },
  '249': { name: 'Ontario, Canada' },
  '250': { name: 'British Columbia, Canada' },
  '251': { name: 'Alabama (Mobile)' },
  '252': { name: 'North Carolina (Greenville, Rocky Mount)' },
  '253': { name: 'Washington (Tacoma)' },
  '254': { name: 'Texas (Waco, Killeen)' },
  '255': UNUSED_NON_GEOGRAPHIC,
  '256': { name: 'Alabama (Huntsville, Decatur)' },
  '257': COMING_SOON,
  '258': UNUSED_GEOGRAPHIC,
  '259': UNUSED_GEOGRAPHIC,
  '300': UNUSED_NON_GEOGRAPHIC,
  '301': { name: 'Maryland (Frederick, Rockville)' },
  '302': { name: 'Delaware' },
  '303': { name: 'Colorado (Denver, Boulder)' },
  '304': { name: 'West Virginia' },
  '305': { name: 'Florida (Miami, Keys)' },
  '306': { name: 'Saskatchewan, Canada' },
  '307': { name: 'Wyoming' },
  '308': { name: 'Nebraska' },
  '309': { name: 'Illinois (Peoria, Bloomington)' },
  '310': { name: 'California (Santa Monica, Torrance)' },
  '311': N11,
  '312': { name: 'Illinois (Chicago)' },
  '313': { name: 'Michigan (Detroit)' },
  '314': { name: 'Missouri (St. Louis)' },
  '315': { name: 'New York (Syracuse, Utica)' },
  '316': { name: 'Kansas (Wichita)' },
  '317': { name: 'Indiana (Indianapolis)' },
  '318': { name: 'Louisiana (Shreveport, Monroe)' },
  '319': { name: 'Iowa (Cedar Rapids, Waterloo)' },
  '320': { name: 'Minnesota (St. Cloud)' },
  '321': { name: 'Florida (Orlando, Space Coast)' },
  '322': UNUSED_NON_GEOGRAPHIC,
  '323': { name: 'California (Los Angeles)' },
  '324': { name: 'Florida (Jacksonville)' },
  '325': { name: 'Texas (Abilene, San Angelo)' },
  '326': { name: 'Ohio' },
  '327': { name: 'Arkansas' },
  '328': UNUSED_GEOGRAPHIC,
  '329': { name: 'New York' },
  '330': { name: 'Ohio (Akron, Canton)' },
  '331': { name: 'Illinois' },
  '332': { name: 'New York City (Manhattan)' },
  '333': UNUSED_NON_GEOGRAPHIC,
  '334': { name: 'Alabama (Montgomery, Dothan)' },
  '335': UNUSED_GEOGRAPHIC,
  '336': { name: 'North Carolina (Greensboro, Winston-Salem)' },
  '337': { name: 'Louisiana (Lafayette, Lake Charles)' },
  '338': UNUSED_GEOGRAPHIC,
  '339': { name: 'Massachusetts' },
  '340': { name: 'U.S. Virgin Islands' },
  '341': { name: 'California' },
  '342': UNUSED_GEOGRAPHIC,
  '343': { name: 'Ontario, Canada' },
  '344': UNUSED_NON_GEOGRAPHIC,
  '345': { name: 'Cayman Islands' },
  '346': { name: 'Texas (Houston)' },
  '347': { name: 'New York City (Brooklyn, Queens)' },
  '348': UNUSED_GEOGRAPHIC,
  '349': UNUSED_GEOGRAPHIC,
  '350': { name: 'California' },
  '351': { name: 'Massachusetts' },
  '352': { name: 'Florida (Gainesville, Ocala)' },
  '353': { name: 'Wisconsin (Madison, La Crosse)' },
  '354': { name: 'Quebec, Canada' },
  '355': UNUSED_NON_GEOGRAPHIC,
  '356': UNUSED_GEOGRAPHIC,
  '357': COMING_SOON,
  '358': UNUSED_GEOGRAPHIC,
  '359': UNUSED_GEOGRAPHIC,
  '400': UNUSED_NON_GEOGRAPHIC,
  '401': { name: 'Rhode Island' },
  '402': { name: 'Nebraska (Omaha, Lincoln)' },
  '403': { name: 'Alberta (Calgary)' },
  '404': { name: 'Georgia (Atlanta)' },
  '405': { name: 'Oklahoma (Oklahoma City)' },
  '406': { name: 'Montana' },
  '407': { name: 'Florida (Orlando)' },
  '408': { name: 'California (San Jose, Sunnyvale)' },
  '409': { name: 'Texas (Beaumont, Galveston)' },
  '410': { name: 'Maryland (Baltimore)' },
  '411': N11,
  '412': { name: 'Pennsylvania (Pittsburgh)' },
  '413': { name: 'Massachusetts (Springfield)' },
  '414': { name: 'Wisconsin (Milwaukee)' },
  '415': { name: 'California (San Francisco)' },
  '416': { name: 'Ontario (Toronto)' },
  '417': { name: 'Missouri (Springfield, Joplin)' },
  '418': { name: 'Quebec (Quebec City)' },
  '419': { name: 'Ohio (Toledo)' },
  '420': UNUSED_GEOGRAPHIC,
  '421': UNUSED_GEOGRAPHIC,
  '422': UNUSED_NON_GEOGRAPHIC,
  '423': { name: 'Tennessee (Chattanooga, Johnson City)' },
  '424': { name: 'California' },
  '425': { name: 'Washington (Bellevue, Everett)' },
  '426': UNUSED_GEOGRAPHIC,
  '427': UNUSED_GEOGRAPHIC,
  '428': { name: 'New Brunswick, Canada' },
  '429': UNUSED_GEOGRAPHIC,
  '430': { name: 'Texas' },
  '431': { name: 'Manitoba' },
  '432': { name: 'Texas' },
  '433': UNUSED_NON_GEOGRAPHIC,
  '434': { name: 'Virginia' },
  '435': { name: 'Utah' },
  '436': { name: 'Ohio' },
  '437': { name: 'Ontario, Canada' },
  '438': { name: 'Montreal, Quebec' },
  '439': UNUSED_GEOGRAPHIC,
  '440': { name: 'Ohio' },
  '441': { name: 'Bermuda' },
  '442': { name: 'California' },
  '443': { name: 'Maryland' },
  '444': UNUSED_NON_GEOGRAPHIC,
  '445': { name: 'Pennsylvania (Philadelphia)' },
  '446': UNUSED_GEOGRAPHIC,
  '447': { name: 'Illinois (Springfield)' },
  '448': { name: 'Florida (Panhandle - Tallahassee, Pensacola)' },
  '449': UNUSED_GEOGRAPHIC,
  '450': { name: 'Quebec, Canada' },
  '451': UNUSED_GEOGRAPHIC,
  '452': UNUSED_GEOGRAPHIC,
  '453': UNUSED_GEOGRAPHIC,
  '454': UNUSED_GEOGRAPHIC,
  '455': UNUSED_NON_GEOGRAPHIC,
  '456': UNUSED_GEOGRAPHIC,
  '457': COMING_SOON,
  '458': { name: 'Oregon' },
  '459': UNUSED_GEOGRAPHIC,
  '500': PERSONAL_COMMUNICATIONS,
  '501': { name: 'Arkansas (Little Rock)' },
  '502': { name: 'Kentucky (Louisville, Frankfort)' },
  '503': { name: 'Oregon (Portland)' },
  '504': { name: 'Louisiana (New Orleans)' },
  '505': { name: 'New Mexico' },
  '506': { name: 'New Brunswick, Canada' },
  '507': { name: 'Minnesota (Rochester, Mankato)' },
  '508': { name: 'Massachusetts (Worcester, New Bedford)' },
  '509': { name: 'Washington (Spokane, Yakima)' },
  '510': { name: 'California (Oakland, Berkeley)' },
  '511': N11,
  '512': { name: 'Texas (Austin)' },
  '513': { name: 'Ohio (Cincinnati)' },
  '514': { name: 'Quebec (Montreal)' },
  '515': { name: 'Iowa (Des Moines, Ames)' },
  '516': { name: 'New York (Long Island, Nassau County)' },
  '517': { name: 'Michigan (Lansing, Jackson)' },
  '518': { name: 'New York (Albany, Schenectady)' },
  '519': { name: 'Ontario (London, Windsor)' },
  '520': { name: 'Arizona (Tucson)' },
  '521': PERSONAL_COMMUNICATIONS,
  '522': PERSONAL_COMMUNICATIONS,
  '523': PERSONAL_COMMUNICATIONS,
  '524': PERSONAL_COMMUNICATIONS,
  '525': PERSONAL_COMMUNICATIONS,
  '526': PERSONAL_COMMUNICATIONS,
  '527': PERSONAL_COMMUNICATIONS,
  '528': PERSONAL_COMMUNICATIONS,
  '529': PERSONAL_COMMUNICATIONS,
  '530': { name: 'California (Redding, Chico)' },
  '531': { name: 'Nebraska' },
  '532': PERSONAL_COMMUNICATIONS,
  '533': PERSONAL_COMMUNICATIONS,
  '534': { name: 'Wisconsin' },
  '535': PERSONAL_COMMUNICATIONS,
  '536': UNUSED_GEOGRAPHIC,
  '537': COMING_SOON,
  '538': PERSONAL_COMMUNICATIONS,
  '539': { name: 'Oklahoma' },
  '540': { name: 'Virginia (Roanoke, Fredericksburg)' },
  '541': { name: 'Oregon (Eugene, Bend)' },
  '542': PERSONAL_COMMUNICATIONS,
  '543': PERSONAL_COMMUNICATIONS,
  '544': PERSONAL_COMMUNICATIONS,
  '545': PERSONAL_COMMUNICATIONS,
  '546': PERSONAL_COMMUNICATIONS,
  '547': PERSONAL_COMMUNICATIONS,
  '548': { name: 'Ontario, Canada' },
  '549': PERSONAL_COMMUNICATIONS,
  '550': PERSONAL_COMMUNICATIONS,
  '551': { name: 'New Jersey' },
  '552': PERSONAL_COMMUNICATIONS,
  '553': PERSONAL_COMMUNICATIONS,
  '554': PERSONAL_COMMUNICATIONS,
  '555': DIRECTORY_ASSISTANCE,
  '556': PERSONAL_COMMUNICATIONS,
  '557': { name: 'Missouri' },
  '558': PERSONAL_COMMUNICATIONS,
  '559': { name: 'California (Fresno, Visalia)' },
  '600': CANADIAN_NON_GEOGRAPHIC,
  '601': { name: 'Mississippi (Jackson, Hattiesburg)' },
  '602': { name: 'Arizona (Phoenix)' },
  '603': { name: 'New Hampshire' },
  '604': { name: 'British Columbia (Vancouver)' },
  '605': { name: 'South Dakota' },
  '606': { name: 'Kentucky (Ashland, Morehead)' },
  '607': { name: 'New York (Binghamton, Elmira)' },
  '608': { name: 'Wisconsin (Madison, La Crosse)' },
  '609': { name: 'New Jersey (Trenton, Atlantic City)' },
  '610': { name: 'Pennsylvania (Allentown, Reading)' },
  '611': N11,
  '612': { name: 'Minnesota (Minneapolis)' },
  '613': { name: 'Ontario (Ottawa, Kingston)' },
  '614': { name: 'Ohio (Columbus)' },
  '615': { name: 'Tennessee (Nashville)' },
  '616': { name: 'Michigan (Grand Rapids)' },
  '617': { name: 'Massachusetts (Boston, Cambridge)' },
  '618': { name: 'Illinois (Carbondale, Belleville)' },
  '619': { name: 'California (San Diego)' },
  '620': { name: 'Kansas' },
  '621': COMING_SOON,
  '622': CANADIAN_NON_GEOGRAPHIC,
  '623': { name: 'Arizona' },
  '624': { name: 'New York (Buffalo, Niagara Falls)' },
  '625': UNUSED_GEOGRAPHIC,
  '626': { name: 'California' },
  '627': UNUSED_GEOGRAPHIC,
  '628': { name: 'California' },
  '629': { name: 'Tennessee' },
  '630': { name: 'Illinois' },
  '631': { name: 'New York (Long Island - Suffolk County)' },
  '632': UNUSED_GEOGRAPHIC,
  '633': CANADIAN_NON_GEOGRAPHIC,
  '634': UNUSED_GEOGRAPHIC,
  '635': UNUSED_GEOGRAPHIC,
  '636': { name: 'Missouri' },
  '637': UNUSED_GEOGRAPHIC,
  '638': UNUSED_GEOGRAPHIC,
  '639': { name: 'Saskatchewan, Canada' },
  '640': { name: 'New Jersey' },
  '641': { name: 'Iowa' },
  '642': UNUSED_GEOGRAPHIC,
  '643': UNUSED_GEOGRAPHIC,
  '644': UNUSED_NON_GEOGRAPHIC,
  '645': { name: 'Florida (Miami-Dade County, Florida Keys)' },
  '646': { name: 'New York City (Manhattan)' },
  '647': { name: 'Ontario, Canada' },
  '648': UNUSED_GEOGRAPHIC,
  '649': { name: 'Turks and Caicos Islands' },
  '650': { name: 'California (San Mateo, Palo Alto)' },
  '651': { name: 'Minnesota' },
  '652': UNUSED_GEOGRAPHIC,
  '653': UNUSED_GEOGRAPHIC,
  '654': UNUSED_GEOGRAPHIC,
  '655': UNUSED_NON_GEOGRAPHIC,
  '656': { name: 'Florida (Tampa)' },
  '657': { name: 'California' },
  '658': { name: 'Jamaica' },
  '659': { name: 'Alabama' },
  '700': CARRIER_INTERNAL_USE,
  '701': { name: 'North Dakota' },
  '702': { name: 'Nevada (Las Vegas)' },
  '703': { name: 'Virginia (Arlington, Alexandria)' },
  '704': { name: 'North Carolina (Charlotte)' },
  '705': { name: 'Ontario (Sudbury, Barrie)' },
  '706': { name: 'Georgia (Augusta, Athens)' },
  '707': { name: 'California (Santa Rosa, Napa)' },
  '708': { name: 'Illinois (Oak Lawn, Cicero)' },
  '709': { name: 'Newfoundland and Labrador' },
  '710': US_GOV_SPECIAL_SERVICES,
  '711': N11,
  '712': { name: 'Iowa (Sioux City, Council Bluffs)' },
  '713': { name: 'Texas (Houston)' },
  '714': { name: 'California (Anaheim, Santa Ana)' },
  '715': { name: 'Wisconsin (Wausau, Eau Claire)' },
  '716': { name: 'New York (Buffalo, Niagara Falls)' },
  '717': { name: 'Pennsylvania (Harrisburg, Lancaster)' },
  '718': { name: 'New York City (Brooklyn, Queens, Staten Island)' },
  '719': { name: 'Colorado (Colorado Springs, Pueblo)' },
  '720': { name: 'Colorado (Denver)' },
  '721': { name: 'Sint Maarten' },
  '722': UNUSED_NON_GEOGRAPHIC,
  '723': UNUSED_GEOGRAPHIC,
  '724': { name: 'Pennsylvania (Greensburg, Beaver Falls)' },
  '725': { name: 'Nevada (Las Vegas)' },
  '726': { name: 'Texas (San Antonio)' },
  '727': { name: 'Florida (St. Petersburg, Clearwater)' },
  '728': { name: 'Florida (Palm Beach County)' },
  '729': COMING_SOON,
  '730': { name: 'Illinois (Carbondale)' },
  '731': { name: 'Tennessee (Jackson)' },
  '732': { name: 'New Jersey (New Brunswick, Toms River)' },
  '733': UNUSED_NON_GEOGRAPHIC,
  '734': { name: 'Michigan (Ann Arbor, Monroe)' },
  '735': UNUSED_GEOGRAPHIC,
  '736': UNUSED_GEOGRAPHIC,
  '737': { name: 'Texas (Austin)' },
  '738': { name: 'California (Los Angeles)' },
  '739': UNUSED_GEOGRAPHIC,
  '740': { name: 'Ohio (Lancaster, Marietta)' },
  '741': UNUSED_GEOGRAPHIC,
  '742': { name: 'Ontario (Toronto)' },
  '743': { name: 'North Carolina' },
  '744': UNUSED_NON_GEOGRAPHIC,
  '745': UNUSED_GEOGRAPHIC,
  '746': UNUSED_GEOGRAPHIC,
  '747': { name: 'California' },
  '748': COMING_SOON,
  '749': UNUSED_GEOGRAPHIC,
  '750': UNUSED_GEOGRAPHIC,
  '751': UNUSED_GEOGRAPHIC,
  '752': UNUSED_GEOGRAPHIC,
  '753': { name: 'Ontario (Ottawa)' },
  '754': { name: 'Florida' },
  '755': UNUSED_NON_GEOGRAPHIC,
  '756': UNUSED_GEOGRAPHIC,
  '757': { name: 'Virginia (Virginia Beach, Norfolk)' },
  '758': { name: 'Saint Lucia' },
  '759': UNUSED_GEOGRAPHIC,
  '800': TOLL_FREE,
  '801': { name: 'Utah (Salt Lake City)' },
  '802': { name: 'Vermont' },
  '803': { name: 'South Carolina' },
  '804': { name: 'Virginia (Richmond)' },
  '805': { name: 'California (Santa Barbara, San Luis Obispo)' },
  '806': { name: 'Texas (Lubbock, Amarillo)' },
  '807': { name: 'Ontario (Thunder Bay)' },
  '808': { name: 'Hawaii' },
  '809': { name: 'Dominican Republic' },
  '810': { name: 'Michigan' },
  '811': N11,
  '812': { name: 'Indiana' },
  '813': { name: 'Florida (Tampa)' },
  '814': { name: 'Pennsylvania (Erie, Altoona)' },
  '815': { name: 'Illinois (Rockford, Joliet)' },
  '816': { name: 'Missouri (Kansas City)' },
  '817': { name: 'Texas (Fort Worth, Arlington)' },
  '818': { name: 'California (San Fernando Valley)' },
  '819': { name: 'Quebec, Canada' },
  '820': { name: 'California (Ventura)' },
  '821': { name: 'South Carolina' },
  '822': TOLL_FREE,
  '823': UNUSED_GEOGRAPHIC,
  '824': UNUSED_GEOGRAPHIC,
  '825': { name: 'Alberta, Canada' },
  '826': { name: 'Virginia' },
  '827': UNUSED_GEOGRAPHIC,
  '828': { name: 'North Carolina' },
  '829': { name: 'Dominican Republic' },
  '830': { name: 'Texas' },
  '831': { name: 'California' },
  '832': { name: 'Texas (Houston)' },
  '833': TOLL_FREE,
  '834': UNUSED_GEOGRAPHIC,
  '835': { name: 'Pennsylvania' },
  '836': UNUSED_GEOGRAPHIC,
  '837': COMING_SOON,
  '838': { name: 'New York' },
  '839': { name: 'South Carolina' },
  '840': { name: 'California' },
  '841': UNUSED_GEOGRAPHIC,
  '842': UNUSED_GEOGRAPHIC,
  '843': { name: 'South Carolina' },
  '844': TOLL_FREE,
  '845': { name: 'New York' },
  '846': UNUSED_GEOGRAPHIC,
  '847': { name: 'Illinois (Waukegan, Arlington Heights)' },
  '848': { name: 'New Jersey' },
  '849': { name: 'Dominican Republic' },
  '850': { name: 'Florida (Panhandle - Tallahassee, Pensacola)' },
  '851': COMING_SOON,
  '852': UNUSED_GEOGRAPHIC,
  '853': UNUSED_GEOGRAPHIC,
  '854': { name: 'South Carolina' },
  '855': TOLL_FREE,
  '856': { name: 'New Jersey' },
  '857': { name: 'Massachusetts' },
  '858': { name: 'California (San Diego)' },
  '859': { name: 'Kentucky' },
  '900': PREMIUM_RATE,
  '901': { name: 'Tennessee (Memphis)' },
  '902': { name: 'Nova Scotia & PEI' },
  '903': { name: 'Texas' },
  '904': { name: 'Florida (Jacksonville)' },
  '905': { name: 'Ontario (Niagara Falls, Hamilton)' },
  '906': { name: 'Michigan (Upper Peninsula)' },
  '907': { name: 'Alaska' },
  '908': { name: 'New Jersey (Somerville, Plainfield)' },
  '909': { name: 'California (San Bernardino, Riverside)' },
  '910': { name: 'North Carolina (Fayetteville, Wilmington)' },
  '911': N11,
  '912': { name: 'Georgia (Savannah, Brunswick)' },
  '913': { name: 'Kansas (Kansas City)' },
  '914': { name: 'New York (Westchester County)' },
  '915': { name: 'Texas (El Paso)' },
  '916': { name: 'California (Sacramento)' },
  '917': { name: 'New York City (Mobile and Paging)' },
  '918': { name: 'Oklahoma (Tulsa)' },
  '919': { name: 'North Carolina (Raleigh, Durham)' },
  '920': { name: 'Wisconsin (Green Bay, Appleton)' },
  '921': UNUSED_GEOGRAPHIC,
  '922': UNUSED_NON_GEOGRAPHIC,
  '923': UNUSED_GEOGRAPHIC,
  '924': { name: 'Minnesota (Rochester)' },
  '925': { name: 'California (Concord, Livermore)' },
  '926': UNUSED_GEOGRAPHIC,
  '927': UNUSED_GEOGRAPHIC,
  '928': { name: 'Arizona (Flagstaff, Yuma)' },
  '929': { name: 'New York City (Bronx, Brooklyn)' },
  '930': { name: 'Indiana' },
  '931': { name: 'Tennessee' },
  '932': UNUSED_GEOGRAPHIC,
  '933': UNUSED_NON_GEOGRAPHIC,
  '934': { name: 'New York (Long Island)' },
  '935': UNUSED_GEOGRAPHIC,
  '936': { name: 'Texas' },
  '937': { name: 'Ohio (Dayton, Springfield)' },
  '938': { name: 'Alabama' },
  '939': { name: 'Puerto Rico' },
  '940': { name: 'Texas' },
  '941': { name: 'Florida (Sarasota, Bradenton)' },
  '942': COMING_SOON,
  '943': { name: 'Georgia (Atlanta)' },
  '944': UNUSED_NON_GEOGRAPHIC,
  '945': { name: 'Texas (Dallas)' },
  '946': UNUSED_GEOGRAPHIC,
  '947': { name: 'Michigan' },
  '948': { name: 'Virginia (Virginia Beach, Norfolk)' },
  '949': { name: 'California (Irvine, Mission Viejo)' },
  '950': NOT_ASSIGNABLE,
  '951': { name: 'California (Riverside, Corona)' },
  '952': { name: 'Minnesota' },
  '953': UNUSED_GEOGRAPHIC,
  '954': { name: 'Florida (Fort Lauderdale)' },
  '955': UNUSED_NON_GEOGRAPHIC,
  '956': { name: 'Texas (Laredo, McAllen)' },
  '957': UNUSED_GEOGRAPHIC,
  '958': UNUSED_GEOGRAPHIC,
  '959': { name: 'Connecticut' },
}
