type AreaCodes = Record<string, string>

export const AREA_CODES_MAP: AreaCodes = {
  '201': 'New Jersey (Jersey City)',
  '202': 'Washington, D.C.',
  '203': 'Connecticut (New Haven, Stamford)',
  '204': 'Manitoba, Canada',
  '205': 'Alabama (Birmingham, Tuscaloosa)',
  '206': 'Washington (Seattle)',
  '207': 'Maine',
  '208': 'Idaho',
  '209': 'California (Stockton, Modesto)',
  '210': 'Texas (San Antonio)',
  '212': 'New York City (Manhattan)',
  '213': 'California (Los Angeles)',
  '214': 'Texas (Dallas)',
  '215': 'Pennsylvania (Philadelphia)',
  '216': 'Ohio (Cleveland)',
  '217': 'Illinois (Springfield, Champaign)',
  '218': 'Minnesota (Duluth)',
  '219': 'Indiana (Gary, Hammond)',
  '220': 'Ohio',
  '223': 'Pennsylvania',
  '224': 'Illinois',
  '225': 'Louisiana (Baton Rouge)',
  '226': 'Ontario, Canada',
  '227': 'Maryland',
  '228': 'Mississippi (Gulfport, Biloxi)',
  '229': 'Georgia (Albany, Valdosta)',
  '231': 'Michigan (Traverse City, Muskegon)',
  '234': 'Ohio',
  '235': 'Missouri',
  '236': 'British Columbia, Canada',
  '239': 'Florida (Fort Myers, Naples)',
  '240': 'Maryland',
  '242': 'Bahamas',
  '246': 'Barbados',
  '248': 'Michigan (Pontiac, Troy)',
  '249': 'Ontario, Canada',
  '250': 'British Columbia, Canada',
  '251': 'Alabama (Mobile)',
  '252': 'North Carolina (Greenville, Rocky Mount)',
  '253': 'Washington (Tacoma)',
  '254': 'Texas (Waco, Killeen)',
  '256': 'Alabama (Huntsville, Decatur)',
  // May 2025
  // '257': "British Columbia, Canada",
  '301': 'Maryland (Frederick, Rockville)',
  '302': 'Delaware',
  '303': 'Colorado (Denver, Boulder)',
  '304': 'West Virginia',
  '305': 'Florida (Miami, Keys)',
  '306': 'Saskatchewan, Canada',
  '307': 'Wyoming',
  '308': 'Nebraska',
  '309': 'Illinois (Peoria, Bloomington)',
  '310': 'California (Santa Monica, Torrance)',
  '312': 'Illinois (Chicago)',
  '313': 'Michigan (Detroit)',
  '314': 'Missouri (St. Louis)',
  '315': 'New York (Syracuse, Utica)',
  '316': 'Kansas (Wichita)',
  '317': 'Indiana (Indianapolis)',
  '318': 'Louisiana (Shreveport, Monroe)',
  '319': 'Iowa (Cedar Rapids, Waterloo)',
  '320': 'Minnesota (St. Cloud)',
  '321': 'Florida (Orlando, Space Coast)',
  '323': 'California (Los Angeles)',
  '324': 'Florida (Jacksonville)',
  '325': 'Texas (Abilene, San Angelo)',
  '326': 'Ohio',
  '327': 'Arkansas',
  '329': 'New York',
  '330': 'Ohio (Akron, Canton)',
  '331': 'Illinois',
  '332': 'New York City (Manhattan)',
  '334': 'Alabama (Montgomery, Dothan)',
  '336': 'North Carolina (Greensboro, Winston-Salem)',
  '337': 'Louisiana (Lafayette, Lake Charles)',
  '339': 'Massachusetts',
  '340': 'U.S. Virgin Islands',
  '341': 'California',
  '343': 'Ontario, Canada',
  '345': 'Cayman Islands',
  '346': 'Texas (Houston)',
  '347': 'New York City (Brooklyn, Queens)',
  '350': 'California',
  '351': 'Massachusetts',
  '352': 'Florida (Gainesville, Ocala)',
  '353': 'Wisconsin (Madison, La Crosse)',
  '354': 'Quebec, Canada',
  '401': 'Rhode Island',
  '402': 'Nebraska (Omaha, Lincoln)',
  '403': 'Alberta, Canada (Calgary)',
  '404': 'Georgia (Atlanta)',
  '405': 'Oklahoma (Oklahoma City)',
  '406': 'Montana',
  '407': 'Florida (Orlando)',
  '408': 'California (San Jose, Sunnyvale)',
  '409': 'Texas (Beaumont, Galveston)',
  '410': 'Maryland (Baltimore)',
  '412': 'Pennsylvania (Pittsburgh)',
  '413': 'Massachusetts (Springfield)',
  '414': 'Wisconsin (Milwaukee)',
  '415': 'California (San Francisco)',
  '416': 'Ontario, Canada (Toronto)',
  '417': 'Missouri (Springfield, Joplin)',
  '418': 'Quebec, Canada (Quebec City)',
  '419': 'Ohio (Toledo)',
  '423': 'Tennessee (Chattanooga, Johnson City)',
  '424': 'California',
  '425': 'Washington (Bellevue, Everett)',
  '428': 'New Brunswick, Canada',
  '430': 'Texas',
  '432': 'Texas',
  '434': 'Virginia',
  '435': 'Utah',
  '436': 'Ohio',
  '437': 'Ontario, Canada',
  '438': 'Montreal, Quebec',
  '440': 'Ohio',
  '441': 'Bermuda',
  '442': 'California',
  '443': 'Maryland',
  '445': 'Pennsylvania (Philadelphia)',
  '447': 'Illinois (Springfield)',
  '448': 'Florida (Panhandle - Tallahassee, Pensacola)',
  '450': 'Quebec, Canada',
  '458': 'Oregon',
  '501': 'Arkansas (Little Rock)',
  '502': 'Kentucky (Louisville, Frankfort)',
  '503': 'Oregon (Portland)',
  '504': 'Louisiana (New Orleans)',
  '505': 'New Mexico',
  '506': 'New Brunswick, Canada',
  '507': 'Minnesota (Rochester, Mankato)',
  '508': 'Massachusetts (Worcester, New Bedford)',
  '509': 'Washington (Spokane, Yakima)',
  '510': 'California (Oakland, Berkeley)',
  '512': 'Texas (Austin)',
  '513': 'Ohio (Cincinnati)',
  '514': 'Quebec, Canada (Montreal)',
  '515': 'Iowa (Des Moines, Ames)',
  '516': 'New York (Long Island - Nassau County)',
  '517': 'Michigan (Lansing, Jackson)',
  '518': 'New York (Albany, Schenectady)',
  '519': 'Ontario, Canada (London, Windsor)',
  '520': 'Arizona (Tucson)',
  '530': 'California (Redding, Chico)',
  '531': 'Nebraska',
  '534': 'Wisconsin',
  '539': 'Oklahoma',
  '540': 'Virginia (Roanoke, Fredericksburg)',
  '541': 'Oregon (Eugene, Bend)',
  '548': 'Ontario, Canada',
  '551': 'New Jersey',
  '557': 'Missouri',
  '559': 'California (Fresno, Visalia)',
  '601': 'Mississippi (Jackson, Hattiesburg)',
  '602': 'Arizona (Phoenix)',
  '603': 'New Hampshire',
  '604': 'British Columbia, Canada (Vancouver)',
  '605': 'South Dakota',
  '606': 'Kentucky (Ashland, Morehead)',
  '607': 'New York (Binghamton, Elmira)',
  '608': 'Wisconsin (Madison, La Crosse)',
  '609': 'New Jersey (Trenton, Atlantic City)',
  '610': 'Pennsylvania (Allentown, Reading)',
  '612': 'Minnesota (Minneapolis)',
  '613': 'Ontario, Canada (Ottawa, Kingston)',
  '614': 'Ohio (Columbus)',
  '615': 'Tennessee (Nashville)',
  '616': 'Michigan (Grand Rapids)',
  '617': 'Massachusetts (Boston, Cambridge)',
  '618': 'Illinois (Carbondale, Belleville)',
  '619': 'California (San Diego)',
  '620': 'Kansas',
  '623': 'Arizona',
  '624': 'New York (Buffalo, Niagara Falls)',
  '626': 'California',
  '628': 'California',
  '629': 'Tennessee',
  '630': 'Illinois',
  '631': 'New York (Long Island - Suffolk County)',
  '636': 'Missouri',
  '639': 'Saskatchewan, Canada',
  '641': 'Iowa',
  '645': 'Florida (Miami-Dade County, Florida Keys)',
  '646': 'New York City (Manhattan)',
  '647': 'Ontario, Canada',
  '649': 'Turks and Caicos Islands',
  '650': 'California (San Mateo, Palo Alto)',
  '651': 'Minnesota',
  '656': 'Florida (Tampa)',
  '657': 'California',
  '659': 'Alabama',
  '701': 'North Dakota',
  '702': 'Nevada (Las Vegas)',
  '703': 'Virginia (Arlington, Alexandria)',
  '704': 'North Carolina (Charlotte)',
  '705': 'Ontario, Canada (Sudbury, Barrie)',
  '706': 'Georgia (Augusta, Athens)',
  '707': 'California (Santa Rosa, Napa)',
  '708': 'Illinois (Oak Lawn, Cicero)',
  '709': 'Newfoundland and Labrador, Canada',
  '712': 'Iowa (Sioux City, Council Bluffs)',
  '713': 'Texas (Houston)',
  '714': 'California (Anaheim, Santa Ana)',
  '715': 'Wisconsin (Wausau, Eau Claire)',
  '716': 'New York (Buffalo, Niagara Falls)',
  '717': 'Pennsylvania (Harrisburg, Lancaster)',
  '718': 'New York City (Brooklyn, Queens, Staten Island)',
  '719': 'Colorado (Colorado Springs, Pueblo)',
  '720': 'Colorado (Denver)',
  '724': 'Pennsylvania (Greensburg, Beaver Falls)',
  '725': 'Nevada (Las Vegas)',
  '727': 'Florida (St. Petersburg, Clearwater)',
  '728': 'Florida (Palm Beach County)',
  '730': 'Illinois (Carbondale)',
  '731': 'Tennessee (Jackson)',
  '732': 'New Jersey (New Brunswick, Toms River)',
  '734': 'Michigan (Ann Arbor, Monroe)',
  '737': 'Texas (Austin)',
  '738': 'California (Los Angeles)',
  '740': 'Ohio (Lancaster, Marietta)',
  '742': 'Toronto, Canada',
  '743': 'North Carolina',
  '747': 'California',
  '753': 'Ontario (Ottawa)',
  '754': 'Florida',
  '757': 'Virginia (Virginia Beach, Norfolk)',
  '758': 'Saint Lucia',
  '801': 'Utah (Salt Lake City)',
  '802': 'Vermont',
  '803': 'South Carolina',
  '804': 'Virginia (Richmond)',
  '805': 'California (Santa Barbara, San Luis Obispo)',
  '806': 'Texas (Lubbock, Amarillo)',
  '807': 'Ontario, Canada (Thunder Bay)',
  '808': 'Hawaii',
  '809': 'Dominican Republic',
  '810': 'Michigan',
  '812': 'Indiana',
  '813': 'Florida (Tampa)',
  '814': 'Pennsylvania (Erie, Altoona)',
  '815': 'Illinois (Rockford, Joliet)',
  '816': 'Missouri (Kansas City)',
  '817': 'Texas (Fort Worth, Arlington)',
  '818': 'California (San Fernando Valley)',
  '819': 'Quebec, Canada',
  '821': 'South Carolina',
  '826': 'Virginia',
  '828': 'North Carolina',
  '829': 'Dominican Republic',
  '830': 'Texas',
  '831': 'California',
  '832': 'Texas (Houston)',
  '835': 'Pennsylvania',
  '838': 'New York',
  '839': 'South Carolina',
  '840': 'California',
  '843': 'South Carolina',
  '845': 'New York',
  '847': 'Illinois (Waukegan, Arlington Heights)',
  '848': 'New Jersey',
  '849': 'Dominican Republic',
  '850': 'Florida (Panhandle - Tallahassee, Pensacola)',
  '854': 'South Carolina',
  '856': 'New Jersey',
  '857': 'Massachusetts',
  '858': 'California (San Diego)',
  '859': 'Kentucky',
  '901': 'Tennessee (Memphis)',
  '902': 'Nova Scotia and Prince Edward Island',
  '903': 'Texas',
  '904': 'Florida (Jacksonville)',
  '905': 'Ontario, Canada (Niagara Falls, Hamilton)',
  '906': 'Michigan (Upper Peninsula)',
  '907': 'Alaska',
  '908': 'New Jersey (Somerville, Plainfield)',
  '909': 'California (San Bernardino, Riverside)',
  '910': 'North Carolina (Fayetteville, Wilmington)',
  '912': 'Georgia (Savannah, Brunswick)',
  '913': 'Kansas (Kansas City)',
  '914': 'New York (Westchester County)',
  '915': 'Texas (El Paso)',
  '916': 'California (Sacramento)',
  '917': 'New York City (Mobile and Paging)',
  '918': 'Oklahoma (Tulsa)',
  '919': 'North Carolina (Raleigh, Durham)',
  '920': 'Wisconsin (Green Bay, Appleton)',
  '924': 'Minnesota (Rochester)',
  '925': 'California (Concord, Livermore)',
  '928': 'Arizona (Flagstaff, Yuma)',
  '929': 'New York City (Bronx, Brooklyn)',
  '930': 'Indiana',
  '931': 'Tennessee',
  '934': 'New York (Long Island)',
  '936': 'Texas',
  '937': 'Ohio (Dayton, Springfield)',
  '938': 'Alabama',
  '939': 'Puerto Rico',
  '940': 'Texas',
  '941': 'Florida (Sarasota, Bradenton)',
  '943': 'Georgia (Atlanta)',
  '945': 'Texas (Dallas)',
  '947': 'Michigan',
  '948': 'Virginia (Virginia Beach, Norfolk)',
  '949': 'California (Irvine, Mission Viejo)',
  '951': 'California (Riverside, Corona)',
  '952': 'Minnesota',
  '954': 'Florida (Fort Lauderdale)',
  '956': 'Texas (Laredo, McAllen)',
  '957': 'New Mexico',
  '959': 'Connecticut',
}

export const EXTRAS = [
  '(260) -> Indiana (Fort Wayne)',
  '(262) -> Wisconsin (Waukesha, Kenosha)',
  '(264) -> Anguilla',
  '(267) -> Pennsylvania',
  '(268) -> Antigua and Barbuda',
  '(269) -> Michigan (Kalamazoo, Battle Creek)',
  '(270) -> Kentucky (Bowling Green, Hopkinsville)',
  '(272) -> Pennsylvania',
  '(276) -> Virginia (Bristol, Martinsville)',
  '(279) -> California',
  '(281) -> Texas (Houston)',
  '(284) -> British Virgin Islands',
  '(289) -> Ontario, Canada',
  '(360) -> Washington (Olympia, Bellingham)',
  '(361) -> Texas (Corpus Christi)',
  '(364) -> Kentucky',
  '(365) -> Ontario, Canada',
  '(367) -> Quebec, Canada',
  '(380) -> Ohio',
  '(385) -> Utah',
  '(386) -> Florida (Daytona Beach, Lake City)',
  '(463) -> Indiana',
  '(464) -> Illinois',
  '(469) -> Texas (Dallas, Plano)',
  '(470) -> Georgia (Atlanta)',
  '(473) -> Grenada',
  '(475) -> Connecticut',
  '(478) -> Georgia (Macon, Warner Robins)',
  '(479) -> Arkansas (Fort Smith, Fayetteville)',
  '(480) -> Arizona (Scottsdale, Mesa)',
  '(484) -> Pennsylvania',
  '(561) -> Florida (West Palm Beach, Boca Raton)',
  '(562) -> California (Long Beach, Whittier)',
  '(563) -> Iowa (Davenport, Dubuque)',
  '(564) -> Washington',
  '(567) -> Ohio',
  '(570) -> Pennsylvania (Scranton, Wilkes-Barre)',
  '(571) -> Virginia',
  '(573) -> Missouri (Jefferson City, Cape Girardeau)',
  '(574) -> Indiana',
  '(575) -> New Mexico',
  '(579) -> Quebec, Canada',
  '(580) -> Oklahoma',
  '(581) -> Quebec, Canada',
  '(585) -> New York (Rochester)',
  '(586) -> Michigan',
  '(661) -> California',
  '(662) -> Mississippi',
  '(664) -> Montserrat',
  '(667) -> Maryland',
  '(669) -> California',
  '(670) -> Northern Mariana Islands',
  '(671) -> Guam',
  '(678) -> Georgia (Atlanta)',
  '(679) -> Michigan',
  '(681) -> West Virginia',
  '(682) -> Texas (Fort Worth, Arlington)',
  '(684) -> American Samoa',
  '(689) -> Florida',
  '(760) -> California (Palm Springs, Victorville)',
  '(762) -> Georgia',
  '(763) -> Minnesota',
  '(765) -> Indiana',
  '(767) -> Dominica',
  '(769) -> Mississippi',
  '(770) -> Georgia (Atlanta suburbs)',
  '(772) -> Florida',
  '(773) -> Illinois (Chicago)',
  '(774) -> Massachusetts',
  '(775) -> Nevada (Reno)',
  '(778) -> British Columbia, Canada',
  '(779) -> Illinois',
  '(780) -> Alberta, Canada',
  '(781) -> Massachusetts',
  '(784) -> Saint Vincent and the Grenadines',
  '(785) -> Kansas',
  '(786) -> Florida (Miami)',
  '(787) -> Puerto Rico',
  '(860) -> Connecticut',
  '(862) -> New Jersey',
  '(863) -> Florida',
  '(864) -> South Carolina',
  '(865) -> Tennessee',
  '(868) -> Trinidad and Tobago',
  '(869) -> Saint Kitts and Nevis',
  '(870) -> Arkansas',
  '(872) -> Illinois',
  '(873) -> Quebec, Canada',
  '(876) -> Jamaica',
  '(878) -> Pennsylvania',
  '(970) -> Colorado (Grand Junction, Fort Collins)',
  '(971) -> Oregon (Portland)',
  '(972) -> Texas (Dallas, Garland)',
  '(973) -> New Jersey (Paterson, Morristown)',
  '(975) -> Missouri',
  '(978) -> Massachusetts (Lowell, Lawrence)',
  '(979) -> Texas',
  '(980) -> North Carolina',
  '(984) -> North Carolina',
  '(985) -> Louisiana',
  '(986) -> Idaho',
  '(989) -> Michigan (Midland, Saginaw)',
]
